### ISSUE TITLE
Bootstrap cards for /stats.

### ISSUE THREAD

**Issue by Dragonshadow14** [DanBot-Hosting/website#2]
Bootstrap cards would fit and look neat for the stats page.

![image](https://user-images.githubusercontent.com/19649813/112763289-b0544800-8fb8-11eb-9e71-c805ecba47eb.png)

https://getbootstrap.com/docs/4.0/components/card/

**Comment by TheTeaCup** [comment]
idea for cards from Nadwiski#3528
Color the background that indicates whether it was VM Outage (Red), Wings Outage (Gold), Online (Green)

**Comment by TheTeaCup** [comment]
done
